-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "eventDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "eventEndTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "eventStartTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
